name: Heuristics CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Algorithms (Silent)
        run: |
          COIN_RESULT=$(python -m cli.main coin 99)
          TSP_RESULT=$(python -m cli.main tsp --iterations 5)

          echo "COIN_RESULT=$COIN_RESULT" >> $GITHUB_ENV
          echo "TSP_RESULT=$TSP_RESULT" >> $GITHUB_ENV

      - name: Show Final Results
        run: |
          echo "=========================="
          echo " FINAL OUTPUTS"
          echo "=========================="
          echo ""
          echo "Coin Result:"
          echo "$COIN_RESULT"
          echo ""
          echo "TSP Result:"
          echo "$TSP_RESULT"