name: Heuristics CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CLI (Coin)
        id: coin
        run: |
          echo "Running Coin Algorithm..."
          RESULT=$(python -m cli.main coin 99)

          echo "COIN_RESULT<<EOF" >> $GITHUB_ENV
          echo "$RESULT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run CLI (TSP)
        id: tsp
        run: |
          echo "Running TSP..."
          RESULT=$(python -m cli.main tsp --iterations 5)

          echo "TSP_RESULT<<EOF" >> $GITHUB_ENV
          echo "$RESULT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV